### ISSUE TITLE
Test with application.properties doesnt work

### ISSUE THREAD

**Issue by arejula27** [prakticas/urlshortener#19]
The test on delivery PortImpl doesnt work cuz the variable apiKey doesnt get the value from the file application.properties-locale .
The command bootRun works, its only the test.

https://github.com/prakticas/urlshortener/blob/segura/delivery/src/test/kotlin/es/unizar/urlshortener/infrastructure/delivery/ValidatorServiceImplTest.kt

**Comment by fjlopez** [comment]
The fix implies a better understanding of how Spring initialises components. You must update your code to:

```kotlin
@Configuration
internal class ValidatorServiceImplConfig {
    @Bean
    fun externalData(): ExternalData = ExternalData()

    @Bean
    fun testValidatorServiceImpl(): ValidatorServiceImpl = ValidatorServiceImpl(externalData())
}

@SpringBootTest(classes = [ValidatorServiceImplConfig::class])
class ValidatorServiceImplTest{

    @Autowired private lateinit var testValidatorServiceImpl: ValidatorServiceImpl

```

Note that `beans`  are created in a specific `configuration` class, and this class is added to `SpringBootTest`.  Hence, when the beans are created are managed by Spring Framework and then the properties are injected in them. Note that you only need to autowire the ValidatorServiceImpl. 

This solves part of the problem.  This test runs in the `delivery` module. Think it as a sandboxed run, so it only can access to files in the `resources` folder of this module. Copy your property files in the `app` module to the folder `delivery\src\test\resources` and that is. It will work as you expect.

**Comment by arejula27** [comment]
I think i didnt understand how spring works, maybe we can talk about it after the next class?

**Comment by fjlopez** [comment]
Spring uses the pattern [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection).  Here is a [nice post](https://www.marcobehler.com/guides/spring-framework#spring-ioc-dependency-container) that will help you to understand how Spring uses this pattern.

> I think i didnt understand how spring works, maybe we can talk about it after the next class?

Of course :-)

**Comment by arejula27** [comment]
It works,nice
