### ISSUE TITLE
Al poner esto en MasiveUrlShortener.kt solo sale "index" en la página Web

### ISSUE THREAD

**Issue by dolansete** [prakticas/urlshortener#26]
```kotlin
@GetMapping
    fun index(model: Model): String {
        model["uuid"] = UUID.randomUUID().toString()
        return "index"
    }
```
Esta función está basada en la del ejemplo https://github.com/UNIZAR-30246-WebEngineering/htmx-sse
En el ejemplo se usa esa función normalmente y devuelve la página de index.html normalmente. No se por que al ponerlo en delivery/src/main/kotlin/es/unizar/urlshortener/infrastructure/delivery/MasiveUrlShortenerController.kt en la clase MasiveUrlShortenerControllerImpl devuelve una página web con sólo la palabra "index".

@fjlopez ¿Algún consejo de cómo utilizar esa función?

El código está puesto en la rama sse-flux

**Comment by fjlopez** [comment]
En el código original esta función está en un [`@Controller` MVC (Modelo, Vista, **Controlador**)](https://github.com/UNIZAR-30246-WebEngineering/htmx-sse/blob/main/src/main/kotlin/es/unizar/htmxsse/DeliveryHttp.kt). Eso quiere decir que espera que haya una **Vista** en [`resources/templates`](https://github.com/UNIZAR-30246-WebEngineering/htmx-sse/blob/main/src/main/resources/templates) que se llame `index.html` a la que inyectará los valores de `model` que es el **Modelo**. 

Como usas `@RestController`, no es MVC, e interpreta que lo que devuelves es literalmente el contenido del `String`.
